version: '3.5'

services:

  db_postgres:
    image: postgres:10.5
    container_name: clix_dashboard_postgres
    ports:
      - '5433:5432'
    volumes:
      - ../clix_dashboard_backend/pg_data:/var/lib/postgresql/data
      - ../clix_dashboard_backend/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d      
    environment:
      - POSTGRES_DB=<db_name>
      - POSTGRES_USER=<admin_name>
      - POSTGRES_PASSWORD=<admin_password>

  flask-api:
    container_name: clix_dashboard_backend
    restart: always
    build:
      context: ../clix_dashboard_backend
      dockerfile: Dockerfile
      args:
        DOCKER_UID: <host user id>  
    ports:
      - "5001:5000"
    volumes:
      - ../clix_dashboard_backend/app:/home/clix_dashboard_backend/app
      - ../clix_dashboard_backend/SchoolImages:/home/clix_dashboard_backend/SchoolImages  
    depends_on:
      - "db_postgres"

  client:
    container_name: clix_dashboard_ui
    build:
      context: ../clix_dashboard_ui
      dockerfile: Dockerfile
    volumes:
      - ../clix_dashboard_ui:/home/node/app
    ports:
      - '3000:3000'
    depends_on:
      - "db_postgres"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_HOST_URL=http://<server ip address>:5001
        
