version: '3.5'

services:

  db_postgres:
    image: postgres:10.5
    container_name: clix_dashboard_postgres
    ports:
      - '5433:5432'
    volumes:
      - /home/clix/CLIxDashboard/clix_dashboard_backend/pg_data:/var/lib/postgresql/data
      - /home/clix/CLIxDashboard/clix_dashboard_backend/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d      
    environment:
      - POSTGRES_DB=<postgres db name>
      - POSTGRES_USER=<postgres db user>
      - POSTGRES_PASSWORD=<postgres db password>

  flask-api:
    container_name: clix_dashboard_backend
    restart: always
    build:
      context: ../clix_dashboard_backend
      dockerfile: Dockerfile
      args:
        DOCKER_UID: <user id of host> 
    expose:
      - "5000"
    ports:
      - "5001:5000"
    volumes:
      - /home/clix/CLIxDashboard/clix_dashboard_backend/app:/home/clix_dashboard_backend/app
      - /home/clix/CLIxDashboard/clix_dashboard_backend/migrations:/home/clix_dashboard_backend/migrations
      - /home/clix/CLIxDashboard/clix_dashboard_backend/SchoolImages:/home/clix_dashboard_backend/SchoolImages  
      - /home/clix/nginx-proxy/nginx-proxy-letsencrypt-data/certs/clixdashboard.tiss.edu:/home/clix_dashboard_backend/app/certificates
    depends_on:
      - "db_postgres"

  client:
    container_name: clix_dashboard_ui
    build:
      context: /home/clix/CLIxDashboard/clix_dashboard_ui
      dockerfile: Dockerfile
    volumes:
      - /home/clix/CLIxDashboard/clix_dashboard_ui/node_modules:/home/node/app/node_modules
      - /home/clix/CLIxDashboard/clix_dashboard_ui/package.json:/home/node/app/package.json
      - /home/clix/CLIxDashboard/clix_dashboard_ui/package-lock.json:/home/node/app/package-lock.json
      - /home/clix/CLIxDashboard/clix_dashboard_ui/public:/home/node/app/public
      - /home/clix/CLIxDashboard/clix_dashboard_ui/src:/home/node/app/src
      - /home/node/app/node_modules  
    ports:
      - '3000:3000'
    depends_on:
      - "flask-api"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      #- REACT_APP_HOST_URL=<Url of backend container>
      #add below lines if you are using nginx-proxy container with letsencrypt
      - VIRTUAL_HOST=<Url of container>
      - VIRTUAL_PORT=<host port of container>
      - LETSENCRYPT_HOST=<hostname of container>
      - LETSENCRYPT_EMAIL=<configured email>

networks:
  default:
    external:
      name: clix-bridge-network
